/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavBar: typeof import('./src/components/admin/AdminNavBar.vue')['default']
    CaptchaSection: typeof import('./src/components/CaptchaSection.vue')['default']
    ChangePasswordModal: typeof import('./src/components/admin/ChangePasswordModal.vue')['default']
    FansChartModal: typeof import('./src/components/FansChartModal.vue')['default']
    FansToast: typeof import('./src/components/FansToast.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    GallerySection: typeof import('./src/components/GallerySection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    ParticleBackground: typeof import('./src/components/ParticleBackground.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleSection: typeof import('./src/components/ScheduleSection.vue')['default']
    ScrollAnimationsDemo: typeof import('./src/components/ScrollAnimationsDemo.vue')['default']
    SonglistManagement: typeof import('./src/components/admin/SonglistManagement.vue')['default']
    SonglistSection: typeof import('./src/components/SonglistSection.vue')['default']
    TailwindDemo: typeof import('./src/components/TailwindDemo.vue')['default']
    TextExploder: typeof import('./src/components/TextExploder.vue')['default']
  }
}
